server:
  port: 8084


spring:
  application:
    name: bankaccount-service
    
  datasource:
    url: jdbc:mysql://localhost:3306/walletdb
    username: root
    password: Abhi@4537
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
      
      